"""add id column

Revision ID: 184660d3fecb
Revises: 7188569f4790
Create Date: 2021-03-11 22:19:29.437675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "184660d3fecb"
down_revision = "7188569f4790"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")

    op.create_table(
        "user",
        sa.Column("id", sa.Integer, nullable=False, autoincrement=True),
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")

    op.create_table(
        "user",
        sa.Column("email", sa.String(length=128), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("email"),
    )
    # ### end Alembic commands ###
